# -*- coding: utf-8 -*-
"""automate_Apriliya-Aniyatuzzuhriya.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRXCpq61iboZuskQg9p8q6AZKKNuaMYS
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
import argparse
import os

# Nama kolom dataset
COLUMN_NAMES = [
    'status_checking_account', 'duration_month', 'credit_history', 'purpose',
    'credit_amount', 'savings_account_bond', 'present_employment_since',
    'installment_rate', 'personal_status_sex', 'other_debtors',
    'present_residence_since', 'property', 'age', 'other_installment_plans',
    'housing', 'number_existing_credits', 'job', 'num_people_liable',
    'telephone', 'foreign_worker', 'risk'
]

def load_data(file_path):
    """Memuat dataset dari file CSV atau URL"""
    print(f"📂 Loading data dari: {file_path}")

    if file_path.startswith('http'):
        df = pd.read_csv(file_path, header=None, names=COLUMN_NAMES)
    else:
        df = pd.read_csv(file_path, header=None, names=COLUMN_NAMES)

    print(f"✅ Data loaded: {df.shape[0]} baris, {df.shape[1]} kolom")
    return df

def preprocess_data(df):
    """Membersihkan dan memproses data"""
    print("\n🔄 Memulai preprocessing...")

    # Copy data
    df_processed = df.copy()

    # 1. Convert target: 1=Good, 0=Bad
    df_processed['risk'] = df_processed['risk'].map({1: 1, 2: 0})
    print("✅ Target risk telah dikonversi")

    # 2. Handle missing values (jika ada)
    for col in df_processed.columns:
        if df_processed[col].dtype == 'object':
            df_processed[col].fillna(df_processed[col].mode()[0], inplace=True)
        else:
            df_processed[col].fillna(df_processed[col].median(), inplace=True)
    print("✅ Missing values telah di-handle")

    # 3. Pisahkan fitur dan target
    X = df_processed.drop('risk', axis=1)
    y = df_processed['risk']

    # 4. Encoding kolom kategorikal
    categorical_cols = X.select_dtypes(include=['object']).columns
    for col in categorical_cols:
        le = LabelEncoder()
        X[col] = le.fit_transform(X[col])
        print(f"✅ Encoding {col}: selesai")

        # 5. Feature scaling
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    X_scaled = pd.DataFrame(X_scaled, columns=X.columns)
    print("✅ Feature scaling selesai")

    # 6. Gabungkan kembali
    final_df = X_scaled.copy()
    final_df['risk'] = y.values

    print(f"\n✅ Preprocessing selesai! Shape akhir: {final_df.shape}")
    return final_df

def save_data(df, output_path):
    """Menyimpan data yang sudah diproses"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df.to_csv(output_path, index=False)
    print(f"💾 Data disimpan di: {output_path}")

def main():
    parser = argparse.ArgumentParser(description='Preprocessing German Credit Dataset')
    parser.add_argument('--input', type=str, required=True,
                       help='Path ke file raw dataset (bisa URL atau local path)')
    parser.add_argument('--output', type=str, required=True,
                       help='Path untuk menyimpan processed dataset')
    # In a Colab environment, we need to pass arguments explicitly
    # rather than letting argparse try to parse sys.argv.
    # Example: args = parser.parse_args(['--input', 'https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data', '--output', 'processed_german_credit.csv'])
    # Fix: Specify an output directory to avoid FileNotFoundError with os.makedirs
    args = parser.parse_args(['--input', 'https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data', '--output', 'output/processed_german_credit.csv'])

    # Jalankan preprocessing
    df = load_data(args.input)
    df_processed = preprocess_data(df)
    save_data(df_processed, args.output)

    print("\n🎉 AUTOMATION SELESAI! Data siap untuk training.")

if __name__ == '__main__':
    main()